<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCLJZOJt\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCLJZOJt/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerCLJZOJt.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerCLJZOJt\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerCLJZOJt\App_KernelTestDebugContainer([
    'container.build_hash' => 'CLJZOJt',
    'container.build_id' => 'c27f7854',
    'container.build_time' => 1648979236,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCLJZOJt');
