<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9qJ1Uzj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9qJ1Uzj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9qJ1Uzj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9qJ1Uzj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9qJ1Uzj\App_KernelDevDebugContainer([
    'container.build_hash' => '9qJ1Uzj',
    'container.build_id' => 'e62abffe',
    'container.build_time' => 1648979228,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9qJ1Uzj');
